name: Flutter Build

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Altere para o nome da sua branch principal, se necessário
  pull_request:
    branches:
      - main  # Altere para o nome da sua branch principal, se necessário

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Ou a versão que você preferir

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'  # Ou uma versão específica do Flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk